---
- name: apt-get update
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600
  become: true
- name: build-dep ruby-full
  apt:
    name: ruby-full
    state: build-dep
  become: true
- name: install libXX-dev
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - zlib1g
    - libreadline-dev
    - libssl-dev
  become: true
